version: '3.9'

services:
  revanced:
    image: nikhilbadyal/docker-py-revanced
    container_name: revanced-builder
    env_file:
      - .env
    read_only: true
    volumes:
      - ./data:/app/apks:rw
